// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppiWorldCup2022.Models
{
    public partial class Coach
    {
        public Coach()
        {
            Incidents = new HashSet<Incidents>();
        }

        public int IdCoach { get; set; }
        public int IdSoccerTeam { get; set; }
        public int IdPerson { get; set; }

        public virtual Person IdPersonNavigation { get; set; }
        public virtual SoccerTeam IdSoccerTeamNavigation { get; set; }
        public virtual ICollection<Incidents> Incidents { get; set; }
    }
}