// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppiWorldCup2022.Models
{
    public partial class Groups
    {
        public Groups()
        {
            SoccerTeam = new HashSet<SoccerTeam>();
        }

        public string NameGroup { get; set; }
        public int IdGroups { get; set; }

        public virtual ICollection<SoccerTeam> SoccerTeam { get; set; }
    }
}