// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppiWorldCup2022.Models
{
    public partial class Instance
    {
        public Instance()
        {
            Match = new HashSet<Match>();
        }

        public int IdInstance { get; set; }
        public string InstanceName { get; set; }

        public virtual ICollection<Match> Match { get; set; }
    }
}