// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppiWorldCup2022.Models
{
    public partial class Match
    {
        public Match()
        {
            Incidents = new HashSet<Incidents>();
            RefereeMatch = new HashSet<RefereeMatch>();
        }

        public int IdMatch { get; set; }
        public int IdStadium { get; set; }
        public int IdInstance { get; set; }
        public int IdScoccerTeamLocal { get; set; }
        public int IdSoccerteamVisit { get; set; }
        public DateTime? MatchDay { get; set; }

        public virtual Instance IdInstanceNavigation { get; set; }
        public virtual SoccerTeam IdScoccerTeamLocalNavigation { get; set; }
        public virtual SoccerTeam IdSoccerteamVisitNavigation { get; set; }
        public virtual Stadium IdStadiumNavigation { get; set; }
        public virtual ICollection<Incidents> Incidents { get; set; }
        public virtual ICollection<RefereeMatch> RefereeMatch { get; set; }
    }
}