// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppiWorldCup2022.Models
{
    public partial class RefereeMatch
    {
        public int IdRefereeMatch { get; set; }
        public int IdReferee { get; set; }
        public int Idmatch { get; set; }
        public string Position { get; set; }

        public virtual Referee IdRefereeNavigation { get; set; }
        public virtual Match IdmatchNavigation { get; set; }
    }
}