// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppiWorldCup2022.Models
{
    public partial class SoccerTeam
    {
        public SoccerTeam()
        {
            Coach = new HashSet<Coach>();
            Incidents = new HashSet<Incidents>();
            MatchIdScoccerTeamLocalNavigation = new HashSet<Match>();
            MatchIdSoccerteamVisitNavigation = new HashSet<Match>();
            Player = new HashSet<Player>();
        }

        public int IdSoccerTeam { get; set; }
        public string Country { get; set; }
        public int? IdGroups { get; set; }
        public int? Goal { get; set; }

        public virtual Groups IdGroupsNavigation { get; set; }
        public virtual ICollection<Coach> Coach { get; set; }
        public virtual ICollection<Incidents> Incidents { get; set; }
        public virtual ICollection<Match> MatchIdScoccerTeamLocalNavigation { get; set; }
        public virtual ICollection<Match> MatchIdSoccerteamVisitNavigation { get; set; }
        public virtual ICollection<Player> Player { get; set; }
    }
}