// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppiWorldCup2022.Models
{
    public partial class Stadium
    {
        public Stadium()
        {
            Match = new HashSet<Match>();
        }

        public int IdStadium { get; set; }
        public string Name { get; set; }
        public string City { get; set; }

        public virtual ICollection<Match> Match { get; set; }
    }
}